### ISSUE TITLE
Fix: 리뷰  관련 API 버그 수정

### ISSUE THREAD

**Issue by hyunji-ch5i15** [BapZip/Backend#122]
## ⚙️ 발생 기능
1. 가게 리뷰 불러오기
2. 리뷰 좋아요 하기
3. 리뷰 삭제하기 
4. 리뷰 조회) 단일 이미지 -> 여러이미지
5. 내가 쓴 글 좋아요 못하게 하기
6. 리뷰 작성 이미지 5개 제한

## ❓ 발생 상황
- 1. 가게 리뷰 불러오기 중 UserReview의 중복 레코드로 인해

>  **"query did not return a unique result: 6"**

 오류 발생 -> 워크밴치에서 중복 레코드 제거 
- 2. 리뷰 좋아요 하기 중 UserReview의 PK가 자동 생성되지 않음 

>  "The database returned no natively generated identity value : com.example.BapZip.domain.mapping.UserReview"

-> 워크밴치에서 id 칼럼 자동 증가와 기본키로 지정함
- 3. 리뷰 삭제 중 외래키 제약 조건으로 review테이블의 행을 삭제할 수 없음 (Review와 Review로 인한 문제) 

> "could not execute statement [Cannot delete or update a parent row: a foreign key constraint fails (babzip.review_image, CONSTRAINT FK16wp089tx9nm0obc217gvdd6l FOREIGN KEY (review_id) REFERENCES review (id))] [/* delete for com.example.BapZip.domain.Review /delete from review where id=?]; SQL [/ delete for com.example.BapZip.domain.Review */delete from review where id=?]; constraint [null]"

 -> Review엔티티 cascade = CascadeType.ALL 추가, ReviewImage엔티티를 images 필드에 추가해 Review엔티티에 저장함 

## 📝 To-do
- [x] 1. 해결 코드: CREATE TABLE UserReviewCopy AS SELECT * FROM UserReview WHERE 1 GROUP BY userId, reviewId; DROP TABLE UserReview;
ALTER TABLE UserReviewCopy RENAME TO UserReview;
- [x] 2. ALTER TABLE user_review MODIFY COLUMN id INT auto_increment PRIMARY KEY;
- [x] 3. Review 엔티티, ReviewServieImpl 수정
- [x] 4. 리뷰 조회) 단일 이미지 -> 여러이미지
- [x] 5. 내가 쓴 글 좋아요 못하게 하기
- [x] 6. 리뷰 작성 이미지 5개 제한

## 💡 예상 응답
어떤 결과를 얻을 것으로 생각했는지 적어주세요.

## ETC
>
