### ISSUE TITLE
Feat: StoreDTO 작성

### ISSUE THREAD

**Issue by hyunji-ch5i15** [BapZip/Backend#30]
## 📌 Feature Issue
Store 관련 DTO를 작성합니다. 

## 📝 To-do
- [ ] 가게 썸네일 request DTO 작성
- [ ] 가게 썸네일 response DTO 작성
- [ ] 가게 정보 request DTO 작성
- [ ] 가게 정보 responseDTO 작성
- [ ] 오늘의 공지 request DTO 작성
- [ ] 오늘의 공지 response DTO 작성 

## ETC
>
