### ISSUE TITLE
Feat: UserDTO 작성

### ISSUE THREAD

**Issue by RhoSeungA** [BapZip/Backend#31]
## 📌 Feature Issue
User 관련 DTO를 작성합니다.

## 📝 To-do
- [ ] 회원가입 request DTO 작성
- [ ] 회원가입 response DTO 작성
- [ ] 로그인 request DTO 작성
- [ ] 로그인 response DTO 작성
- [ ] 약관 동의  request DTO 작성
- [ ] 약관 동의 response DTO 작성
- [ ]  내정보 response DTO 작성

## ETC
>
