### ISSUE TITLE
Feat: 회원가입 관련 api

### ISSUE THREAD

**Issue by RhoSeungA** [BapZip/Backend#54]
## 📌 Feature Issue
회원 가입 관련 api 구현

## 📝 To-do
- [x] 닉네임 중복 확인
- [x] 아이디 중복 확인
- [x] 이용 약관 
- [x]  학과 검색 api
- [x] 학교 리스트 api
- [x] 학교 검색 api
- [x] 학교 지역 리스트 api 

## ETC
>
