### ISSUE TITLE
Feat: Congestion 관련 api

### ISSUE THREAD

**Issue by RhoSeungA** [BapZip/Backend#55]
## 📌 Feature Issue
혼잡도 관련 api 구현

## 📝 To-do
- [x] 혼잡도를 포함한 가게 정보 api 구현
- [x] 혼잡도 등록 api 구현
- [x] 혼잡도 실시간 랭킹 api(전체, 학교 내부, 학교 외부) 구현

## ETC
>
