### ISSUE TITLE
Feat: 가게정보 API 구현,마이페이지 프로필 조회 추가 

### ISSUE THREAD

**Issue by Castleone98** [BapZip/Backend#58]
## 📌 Feature Issue
가게정보 API 구현
마이페이지 프로필 조회 API 추가

## 📝 To-do
- [ ] 가게정보 API 구현
- [ ] UserImage 엔티티 추가 
- [ ] 마이페이지 프로필 이미지 API 구현  

## ETC
>
