### ISSUE TITLE
Feat: 가게 공지,가게 zip api 구현

### ISSUE THREAD

**Issue by RhoSeungA** [BapZip/Backend#83]
## 📌 Feature Issue
가게 공지,가게 zip api 구현

## 📝 To-do
- [ ] 가게 오늘의 공지 api
- [ ] 가게 zip api 
- [ ] 가게 zip 해제 api

## ETC
>
